# using gradle-wrapper

FROM eclipse-temurin:17-jdk-alpine AS build
WORKDIR /app
COPY .gradle ./.gradle
COPY gradle ./gradle
COPY src ./src
COPY gradlew build.gradle settings.gradle ./
RUN ./gradlew build

FROM eclipse-temurin:17-jre-alpine AS app
WORKDIR /app
COPY --from=build /app/build/libs/*.jar ./app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]
