spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: testUser
    password: testPass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
  mvc:
    log-request-details: true
  codec:
    log-request-details: true

logging:
  level:
    root: info
    web: debug
  file:
    name: log/myapp.log
