spring:
  datasource:
    url: jdbc:mysql://localhost:3306/
    username: testUser
    password: testPass
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql
      #      data-locations: classpath: